SELECT *, USER_NAME() AS [CurrentUser] FROM Users

CREATE USER WebUser WITHOUT LOGIN
GRANT SELECT ON Users TO WebUser
GRANT UPDATE ON Users TO WebUser
GRANT UNMASK TO WebUser
REVOKE UNMASK TO WebUser
DROP USER IF EXISTS WebUser

ALTER TABLE Users ALTER COLUMN Password ADD MASKED WITH (FUNCTION = 'partial(1, "XXXXXXX", 0)')
ALTER TABLE Users ALTER COLUMN Login ADD MASKED WITH (FUNCTION = 'email()')
ALTER TABLE Users ALTER COLUMN Login DROP MASKED
ALTER TABLE Users ALTER COLUMN Password DROP MASKED


EXEC AS USER = 'WebUser'
REVERT
SELECT USER_NAME()

SELECT * FROM Users

DROP TABLE IF EXISTS #UserCopy

SELECT * INTO #UserCopy FROM Users

SELECT * FROM #UserCopy

BEGIN TRANSACTION
	UPDATE Users SET Password = '12345' WHERE UserId = 1
	SELECT * FROM Users WHERE Userid = 1
ROLLBACK


