ALTER TABLE Users ADD 
StartDate DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT DF_USERS_START DEFAULT CAST ('1900-01-01' AS DATETIME2),
EndDate DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT DF_USERS_END DEFAULT CAST ('9999-12-31 23:59:59.9999999' AS DATETIME2),
PERIOD FOR SYSTEM_TIME (StartDate, EndDate)
GO

ALTER TABLE Users SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.UsersHistory))

SELECT * FROM Users
SELECT * FROM Users FOR SYSTEM_TIME AS OF '2017-02-03 03:50:25' ORDER BY UserId
SELECT * FROM UsersHistory ORDER BY UserId

UPDATE Users SET Password = 'Test' WHERE UserId = 10
DELETE FROM Users WHERE UserId = 2

DELETE FROM Users WHERE UserId < 10



-- Remove versioning
ALTER TABLE Users SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE Users DROP CONSTRAINT DF_USERS_START
ALTER TABLE Users DROP CONSTRAINT DF_USERS_END
ALTER TABLE Users DROP PERIOD FOR SYSTEM_TIME
ALTER TABLE Users DROP COLUMN StartDate, EndDate
DROP TABLE IF EXISTS UsersHistory
GO