ALTER TABLE Users ADD 
StartDate DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL DEFAULT CAST ('1900-01-01' AS DATETIME2),
EndDate DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL DEFAULT CAST ('9999-12-31 23:59:59.9999999' AS DATETIME2),
PERIOD FOR SYSTEM_TIME (StartDate, EndDate)
GO


ALTER TABLE Users SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.UsersHistory))

SELECT * FROM Users
SELECT * FROM Users FOR SYSTEM_TIME AS OF '2016-10-31 03:45:16' ORDER BY UserId
SELECT * FROM UsersHistory ORDER BY UserId

DELETE FROM Users WHERE UserId = 2

UPDATE Users SET Password = 'Test' WHERE UserId = 2


-- Remove versioning
ALTER TABLE Users SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE Users DROP CONSTRAINT DF__Users__StartDate__38996AB5
ALTER TABLE Users DROP CONSTRAINT DF__Users__EndDate__398D8EEE
ALTER TABLE Users DROP PERIOD FOR SYSTEM_TIME
ALTER TABLE Users DROP COLUMN StartDate, EndDate
GO